name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy on Heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: akhileshns/heroku-deploy@79ef2ae4ff9b897010907016b268fd0f88561820
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "markku63-pokedex"
          heroku_email: "markku.kolkka@iki.fi"
          healthcheck: "https://markku63-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@18284c78f6ac68868d5341f57c4f971fb5b7605c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
      - name: Succesful deployment notification
        if: ${{ success() && github.event_name == 'push' }}
        uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':simple_smile:'
          status: custom
          fields: commit, author, took
          channel: '#code'
          custom_payload: |
            {
              attachments: [
                {
                  fallback: 'Succesful deployment',
                  color: 'good',
                  text: `a new version deployed to https://markku63-pokedex.herokuapp.com (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
      - name: Succesful build and test notification
        if: ${{ success() && github.event_name != 'push' }}
        uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':simple_smile:'
          status: custom
          fields: commit, author, took
          channel: '#code'
          custom_payload: |
            {
              attachments: [
                {
                  fallback: 'Succesful build',
                  color: 'good',
                  text: `a new version (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} built and tested in ${process.env.AS_TOOK}`,
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
      - name: Failure notification
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          icon_emoji: ':collision:'
          status: ${{ job.status }}
          fields: repo, message, commit, author, took
          channel: '#code'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}